services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx42
    ports:
      - "443:443"
    depends_on:
      wordpress
    restart: always



  mariadb:
    build: ./requirements/mariadb
    env_file: .env
    container_name: mariadb42
    volumes:
      - db:/var/lib/mysql
    restart: always



  wordpress:
    build:  ./requirements/wordpress
    env_file: .env
    container_name: wordpress42
    volumes:
      - wp:/var/www/html
    depends_on:
      - mariadb
    restart: always

volumes:
  db:
  wp: